### PR TITLE
Observables Q&A

### PR DESCRIPTION
**Pull request by KlapTrap**
I have moved the observable related question from the redux section and have created an observable Q&A with a slightly modified version of the question.

I can't find the original author of the redux Q&A (Emma Bostian??) so cannot verify if she is ok with the changes.

### CODE REVIEW

**Comment by emmabostian** [comment]
I don't think that Observables needs their own section. They're part of Redux/RxJS right? We could create an RxJS section instead.

**Comment by KlapTrap** [comment]
RxJs has an implementation of observables and are very much their own thing away from redux - see http://reactivex.io/. As an example, Angular uses them quite extensively (see their http client) without a redux style store.

I'd be happy to rename the header to RxJS but there should be a distinction between RxJS/Observables and redux to avoid any confusion.

**Comment by emmabostian** [comment]
Cool, let's leave it as is, thanks!

**Comment by KlapTrap** [comment]
👍 Great project by the way. I'll get around to answering some of the observable questions when I get some time @emmawedekind

**Comment by emmabostian** [comment]
Wonderful thanks a bunch!

**Pull request merged**
