### PR TITLE
Update React: Front-End FAQ

### PR DESCRIPTION
**Pull request by mwaz**
This PR will update the prerequisites of diving into React as the previous PR did not detail that Inheritance is vastly used in React Applications, hence making it a prerequisite for a person who would want to dive into learning React.

### CODE REVIEW

**Comment by mwaz** [comment]
hey @emmawedekind kindly check this out and revert

**Comment by alivenotions** [comment]
Hi! A very good and a much more well-rounded update to what I had added, I just have some points that I would like to discuss.
I think that more than OO concepts, React encourages functional concepts over the object oriented ones.
Extending `React.Component` is just a necessary evil (they need it for `setState`) and React discourages classical inheritance to build components.
I also think that mentioning routing, functional and presentational components or different new terms would feel overwhelming to a beginner. While I agree that all these things are integral to understanding how React works or how one could use it in a proper app, I would argue that a complete beginner would enjoy the process of learning more when they can just start building something (which the official docs encourage right off the bat) without getting too bogged down by jargon.

**Comment by mwaz** [comment]
I do agree with you, However, the question asks _if there are any prerequisites_ and does not necessarily point to the fact that it is only beginners who will be seeking to understand react. It could be an individual who has been writing plain Javascript code with some bit of HTML and CSS. On OOP while it might be a necessary evil it is extensively used, and knowledge of how classes inherit from each other is important. I believe knowledge of routing is important for any individual whether a beginner or a non-beginner, this makes them understand basic concepts before diving into React. During the Sample react documentation it is not well explained what is the difference between SPA and any other applications that use actual urls unlike the dynamic routes used by React. In my opinion, I think these are concepts that will be very much helpful to a person who is interested to learn ReactJS.
Even the [Homepage of React](https://reactjs.org/) point out these factors, in a way or another the user will have to face them in their initial days of learning react

However, we could also add sections for advanced persons and also a part of beginners who are completely new to development.

**Review by emmabostian — APPROVED** [review]
This is great thank you!

**Comment by emmabostian** [comment]
I agree that there are additional requirements than HTML and CSS prior to starting with React!

**Pull request merged**
