### PR TITLE
Answered JS book question

### PR DESCRIPTION
**Pull request by benfurfie**
Added reference to a great book for beginners while leaving a structure that allows – and hopefully encourages – others to continue contributing book suggestions.

### CODE REVIEW

**Comment by SilencerWeb** [comment]
@benfurfie Hm, are you sure it is good for beginners? It contains the word "jQuery".

**Comment by emmabostian** [comment]
I believe it's fine considering it says it provides conversions from jQuery => JS.

Could you please add in the following books:
- https://eloquentjavascript.net/
- https://leanpub.com/javascriptallongesix/read
- https://books.google.de/books/about/Professional_JavaScript_for_Web_Develope.html?id=Wmfr1Zp7d5EC&printsec=frontcover&source=kp_read_button&redir_esc=y#v=onepage&q&f=false

**Review by emmabostian — CHANGES_REQUESTED** [review]
Please see my latest comment.

**Comment by emmabostian** [comment]
Is there any progress on this? Otherwise I'll be closing - thanks.

**Pull request closed without merging**
